"""empty message

Revision ID: 2906793e401f
Revises: 2ad624a7b181
Create Date: 2020-01-10 03:20:03.345621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2906793e401f'
down_revision = '2ad624a7b181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizza', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pizza', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pizza', type_='foreignkey')
    op.drop_column('pizza', 'company_id')
    # ### end Alembic commands ###
