"""empty message

Revision ID: 5a0ba716ca1f
Revises: 
Create Date: 2020-01-09 18:35:23.589188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0ba716ca1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size_s', sa.String(), nullable=True),
    sa.Column('size_m', sa.Integer(), nullable=True),
    sa.Column('size_l', sa.Integer(), nullable=True),
    sa.Column('size_xl', sa.Integer(), nullable=True),
    sa.Column('pizza_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toppings',
    sa.Column('pizza_id', sa.Integer(), nullable=False),
    sa.Column('topping', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizza.id'], ),
    sa.ForeignKeyConstraint(['topping'], ['topping.id'], ),
    sa.PrimaryKeyConstraint('pizza_id', 'topping')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toppings')
    op.drop_table('price')
    op.drop_table('topping')
    op.drop_table('pizza')
    # ### end Alembic commands ###
