"""empty message

Revision ID: e673186292bc
Revises: 
Create Date: 2020-01-14 12:57:15.569454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e673186292bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('delivers', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size_s', sa.String(), nullable=True),
    sa.Column('size_m', sa.Integer(), nullable=True),
    sa.Column('size_l', sa.Integer(), nullable=True),
    sa.Column('size_xl', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pizza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['price.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pizza_topping',
    sa.Column('pizza_id', sa.Integer(), nullable=False),
    sa.Column('topping', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizza.id'], ),
    sa.ForeignKeyConstraint(['topping'], ['topping.id'], ),
    sa.PrimaryKeyConstraint('pizza_id', 'topping')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizza_topping')
    op.drop_table('pizza')
    op.drop_table('topping')
    op.drop_table('price')
    op.drop_table('company')
    # ### end Alembic commands ###
